### ISSUE TITLE
Deployment Error

### ISSUE THREAD

**Issue by Zemerik** [preetsuthar17/dracodemy#1]
Hey, 

> [!Important]
> Your website has not been deployed correctly as users can access it. 

> [!Tip]
> To troubleshoot the problem you may want to redeploy on vercel or maybe delete and create a new project on vercel. 

> [!Note]
> If you are unable to do it through vercel, you can use other hosts such as Github Pages, Cloudfare or Netifly. 

Regards, 
Zemerik

**Comment by preetsuthar17** [comment]
This project has been shut down.

**Comment by Zemerik** [comment]
In that case, I would suggest you archive this repository so that users know that the project has been shutdown.
